# Main composition file for FREE-RADIUS Application Container.
# Author: Arthur Cadore M. Barcella
# Github: arthurcadore

version: '3.8'
services:
  freeradius:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: freeradius
    ports:
      - "1812:1812/udp" # Authentication RADIUS Port
      - "1813:1813/udp" # Accounting RADIUS Port
    volumes:
      - "./config/aaa/:/etc/raddb/mods-config/files/"
      - "./config/clients.conf:/etc/raddb/clients.conf"
      - "./config/sql.conf:/etc/raddb/mods-available/sql"
      - "./config/eap.conf:/etc/raddb/mods-available/eap"
      - "./config/radiusd.conf:/etc/raddb/radiusd.conf"
      - "./config/proxy.conf:/etc/raddb/proxy.conf"
      - "./log/:/var/log/radius/"
      - "./certs:/etc/freeradius/certs"
    restart: always